core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import IndexView, CustomLoginView, CustomLogoutView

urlpatterns = [
    path("", login_required(IndexView.as_view()), name='index'),
    path("supplier/", include('supplier.urls')),
    path("suppli_request/", include('suppli_request.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

supplier/urls.py
from django.urls import path, include

from supplier import views as v

urlpatterns = [
    path("", v.SupplierListView.as_view(), name="supplier-index"),
    path("Detail/<int:pk>/", v.SupplierDetailView.as_view(), name="supplier-detail"),
    path("Update/<int:pk>/", v.SupplierUpdateView.as_view(), name="supplier-update"),
    path("new", v.SupplierCreateView.as_view(), name="supplier-new"),    
    # path("detail", IndexView.as_view(), name="supplier-index"),
    path("ConfirmDelete/<int:pk>/",  v.SupplierDeleteView.as_view(), name="supplier-delete"),
    # CRUD phone_supplier
    path("NewPhoneNumber/<int:int>/", v.PhoneSupplierCreateView.as_view(), name="supplier-createphone"),
    path("UpdatePhoneNumber/<int:pk>/", v.PhoneSupplierUpdateView.as_view(), name="supplier-updatephone"),
    path("Phone/ConfirmDelete/<int:pk>/",  v.PhoneSupplierDeleteView.as_view(), name="supplier-deletephone"),
    # CRUD contact_supplier
    path("NewContact/<int:int>/", v.ContactSupplierCreateView.as_view(), name="supplier-createcontact"),
    path("UpdateContact/<int:pk>/", v.ContactSupplierUpdateView.as_view(), name="supplier-updatecontact"),
    path("Contact/ConfirmDelete/<int:pk>/",  v.ContactSupplierDeleteView.as_view(), name="supplier-deletecontact"),
    # CRUD phone contact_supplier
    path("NewPhoneContact/<int:int>/<int:int2>/", v.PhoneContactCreateView.as_view(), name="supplier-createphonecontact"),
    path("UpdatePhoneContact/<int:pk>/", v.PhoneContactUpdateView.as_view(), name="supplier-updatephonecontact"),
    path("PhoneContact/ConfirmDelete/<int:pk>/",  v.PhoneContactDeleteView.as_view(), name="supplier-deletephonecontact"),
    # CRUD address_supplier
    path("NewAddressNumber/<int:int>", v.AddressSupplierCreateView.as_view(), name="supplier-createaddress"),
    path("UpdateAddressNumber/<int:pk>/", v.AddressSupplierUpdateView.as_view(), name="supplier-updateaddress"),
    path("Address/ConfirmDelete/<int:pk>/",  v.AddressSupplierDeleteView.as_view(), name="supplier-deleteaddress"),
]

supplier/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

USER = get_user_model()


# Abstracts Models
class PhoneBase(models.Model):
    class TypePhoneChoice(models.TextChoices):
        LANDLINE = "LL", _("Telefone Fixo")
        MOBILE = "MB", _("Celular")
    """Model definition for PhoneContact."""
    
    type_phone = models.CharField(_("Telefone"), max_length=2, choices=TypePhoneChoice.choices, default="MB")
    ddi_number = models.CharField(_("DDI"), max_length=3, null=True, blank=True)
    ddd_number = models.CharField(_("DDD"), max_length=2, null=False, blank=False)
    phone_number = models.CharField(_("Número"), max_length=9, null=False, blank=False)

    class Meta:
        abstract = True


class TimeStampBase(models.Model):
    
    created = models.DateTimeField(_("Criado em"), auto_now=False, auto_now_add=True)
    modified = models.DateTimeField(_("Modificado em"), auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(
        USER, 
        verbose_name=_("Usuário"), 
        on_delete=models.CASCADE
    )
    class Meta:
        abstract = True


class AddressBase(models.Model):
    zip_code = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Lougradouro"), max_length=100)
    district = models.CharField(_("Bairro"), max_length=70)
    city = models.CharField(_("Cidade"), max_length=70)
    state = models.CharField(_("UF"), max_length=2)
    ibge_code = models.CharField(_("Código IBGE"), max_length=10)
    gia_code = models.CharField(_("Código GIA"), max_length=6)
    ddd_code = models.CharField(_("Código DDD"), max_length=2)
    siafi_code = models.CharField(_("Código SIAFI"), max_length=6)

    class Meta:
        abstract = True


# Create your models here.
class Supplier(TimeStampBase):   
    """Model definition for Supplier."""
    
    
    is_active = models.BooleanField(_("Ativo"), default=True)
    company_name = models.CharField(_("Razão Social"), max_length=150, null=False, blank=False)
    fantasy_name = models.CharField(_("Nome Fantasia"), max_length=150, null=True, blank=True)
    cnpj_number = models.CharField(_("CNPJ"), max_length=14, null=False, blank=True)
    e_mail = models.EmailField(_("E-mail"), max_length=254, blank=True, null=True)
    class Meta:
        """Meta definition for Supplier."""

        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
    
    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        """Unicode representation of Supplier."""
        if self.fantasy_name:
            return self.fantasy_name.title()
        return self.company_name
    
    def get_active(self):
        active = 1
        print(active)
        return active

class ContactSupplier(models.Model):
    """Model definition for ContactSupplier."""

    supplier_id = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedores"),
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(_("Nome"), max_length=30, null=False, blank=False)
    last_name = models.CharField(_("Sobrenome"), max_length=50, null=True, blank=True)
    position_company = models.CharField(_("Cargo na Empresa"), max_length=50, null=False, blank=False)
    e_mail = models.EmailField(_("E-mail"), max_length=254, null=False, blank=False)
    remarks = models.CharField(_("Observações"), max_length=254, null=True, blank=True)

    class Meta:
        """Meta definition for ContactSupplier."""

        verbose_name = 'Contato do Fornecedor'
        verbose_name_plural = 'Contatos dos Fornecedores'

    @property
    def full_name(self):
        if self.last_name:
            return f'{self.first_name.title()} {self.last_name.title()}'
        return f'{self.first_name.title()}'
    
    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.supplier_id.pk})
    
    def __str__(self):
        """Unicode representation of ContactSupplier."""
        
        return f'{self.full_name.title()} - {self.position_company.title()}'


class PhoneContact(PhoneBase):

    contact = models.ForeignKey(
        ContactSupplier, 
        verbose_name=_("Contato"), 
        on_delete=models.CASCADE,
    )
    
    class Meta:
        """Meta definition for PhoneContact."""

        verbose_name = 'Telefones do Contato'
        verbose_name_plural = 'Telefones dos Contatos'

    def __str__(self):
        """Unicode representation of PhoneContact."""
        if self.ddi_number:
            return f'+{self.ddi_number} ({self.ddd_number}) {self.phone_number}'
        return f'({self.ddd_number}) {self.phone_number}'


class PhoneSupplier(PhoneBase):

    supplier_id = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE,
    )

    class Meta:
        """Meta definition for PhoneContact."""

        verbose_name = 'Telefones do Contato'
        verbose_name_plural = 'Telefones dos Contatos'

    def __str__(self):
        """Unicode representation of PhoneContact."""
        if self.ddi_number:
            return f'+{self.ddi_number} ({self.ddd_number}) {self.phone_number}'
        return f'({self.ddd_number}) {self.phone_number}'

    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.supplier_id.pk})


class ResquestSupplier(models.Model):
    class StatusChoice(models.TextChoices):
        INITIATED = "IT", _("Iniciado")
        PARALYZED = "PL", _("Paralizado")
        INPROGRESS = "IP", _("Em andamento")
        FINISHED = "FN", _("Finalizado")
        COMPLETED = "CP", _("Concluido")    
    """Model definition for ResquestSupplier."""

    supplier_id = models.ForeignKey(
        Supplier,
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE),
    request_date = models.DateField(_("Data da Requisição"), null=False, blank=False)
    reson_hiring = models.CharField(_("Motivo da Contratação"), max_length=254, null=False, blank=False)
    contract_value = models.FloatField(_("Valor Total do Contrato"), null=False, blank=False)
    status = models.CharField(_("Status"), max_length=2, choices=StatusChoice.choices, default="IT")

    class Meta:
        """Meta definition for ResquestSupplier."""

        verbose_name = 'Requisição ao Fornecedor'
        verbose_name_plural = 'Requisições aos Fornecedores'

    def __str__(self):
        """Unicode representation of ResquestSupplier."""
        return f'{self.supplier_id} - Data {self.request_date} - Valor Total R$ {self.contract_value}'


class AddressSupplier(AddressBase):
    class TypeAddressChoice(models.TextChoices):
        RESIDENTIAL = 'RS', _('Residencial')
        COMMERCIAL = 'CM', _('Comercial')
        OTHERS = 'OT', _('Outros')
        
    supplier = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE,
    )
    address_type = models.CharField(_("Tipo de Endereço"), max_length=2, choices=TypeAddressChoice.choices)
    number = models.CharField(_("Número"), max_length=5)
    complement = models.CharField(_("Complemento"), max_length=20, null=True, blank=True)

    class Meta:
        """Meta definition for Supplier."""

        verbose_name = 'Endereço do Fornecedor'
        verbose_name_plural = 'Endereços dos Fornecedores'

    def __str__(self):
        """Unicode representation of Supplier."""
        return f'{self.address_type} - {self.zip_code}-{self.address} {self.number} {self.complement} - {self.city}/{self.state}'

supplier/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from django.utils.translation import gettext as _

from .models import Supplier, PhoneSupplier

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, Row, Column


PhoneSupplierFormset = inlineformset_factory(Supplier, PhoneSupplier, fields=('type_phone', 'ddi_number', 'ddd_number', 'phone_number'), extra=3)


class SupplierForm(forms.ModelForm):
    
    class Meta:
        model = Supplier
        fields = '__all__'


class PhoneSupplierForm(forms.ModelForm):
    
    class Meta:
        model = PhoneSupplier
        fields = '__all__'

supplier/templates/supplier/CRUD/address_supplier/create.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container p-2 mt-4">
    <div class="row"> 
        <div class="col-12"> 
            <div class="card"> 
                <div class="card-header card-no-border pb-0">
                    <h3 class="text-center">Adicionar Endereço do Fornecedor</h3>
                </div>
                <div class="container">
                    <form action="" method="post" class="p-5 m-3">
                        {% csrf_token %}
                        <div id="div_id_address_type" class="mb-3"> 
                            <label for="id_address_type" class="form-label requiredField">Tipo de Endereço
                                <span class="asteriskField">*</span> 
                            </label> 
                            <select name="address_type" class="select form-select" required="" id="id_address_type"> 
                                <option value="" selected="">---------</option> 
                                <option value="RS">Residencial</option> 
                                <option value="CM">Comercial</option>
                                <option value="OT">Outros</option>

                            </select> 
                        </div> 
                        <div id="div_id_zip_code" class="mb-3"> 
                            <label for="id_zip_code" class="form-label requiredField">
                                CEP<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="zip_code" maxlength="9" class="textinput form-control" required="" id="id_zip_code"> 
                        </div>
                        <div class="col-md-2 d-flex align-items-end">
                            <button type="button" class="btn btn-secondary btn-sm" onclick="buscarCEP()">Buscar</button>
                        </div>
                        <!-- Mensagem de erro -->
                        <p id="error-message" style="color: red;"></p>

                        <div id="div_id_address" class="mb-3"> 
                            <label for="id_address" class="form-label requiredField">
                                Lougradouro<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="address" maxlength="100" class="textinput form-control" required="" id="id_address">
                        </div> 
                        <div id="div_id_number" class="mb-3"> 
                            <label for="id_number" class="form-label requiredField">
                                Número<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="number" maxlength="5" class="textinput form-control" required="" id="id_number"> 
                        </div> 
                        <div id="div_id_complement" class="mb-3"> 
                            <label for="id_complement" class="form-label requiredField">
                                Complemento 
                            </label> 
                            <input type="text" name="complement" maxlength="20" class="textinput form-control" id="id_complement"> 
                        </div> 
                        <div id="div_id_district" class="mb-3"> 
                            <label for="id_district" class="form-label requiredField">
                                Bairro<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="district" maxlength="70" class="textinput form-control" required="" id="id_district"> 
                        </div> 
                        <div id="div_id_city" class="mb-3"> 
                            <label for="id_city" class="form-label requiredField">
                                Cidade<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="city" maxlength="70" class="textinput form-control" required="" id="id_city"> 
                        </div> 
                        <div id="div_id_state" class="mb-3"> 
                            <label for="id_state" class="form-label requiredField">
                                UF<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="state" maxlength="2" class="textinput form-control" required="" id="id_state"> 
                        </div> 
                        <div id="div_id_ibge_code" class="mb-3"> 
                            <label for="id_ibge_code" class="form-label requiredField">
                                Código IBGE<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="ibge_code" maxlength="10" class="textinput form-control" required="" id="id_ibge_code"> 
                        </div> 
                        <div id="div_id_gia_code" class="mb-3"> 
                            <label for="id_gia_code" class="form-label requiredField">
                                Código GIA<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="gia_code" maxlength="6" class="textinput form-control" required="" id="id_gia_code"> 
                        </div> 
                        <div id="div_id_ddd_code" class="mb-3"> 
                            <label for="id_ddd_code" class="form-label requiredField">
                                Código DDD<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="ddd_code" maxlength="2" class="textinput form-control" required="" id="id_ddd_code"> 
                        </div>
                        <div id="div_id_siafi_code" class="mb-3"> 
                            <label for="id_siafi_code" class="form-label requiredField">
                                Código SIAFI<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="siafi_code" maxlength="6" class="textinput form-control" required="" id="id_siafi_code"> 
                        </div>
                        <div class="btn-group">
                            <input type="submit" value="Salvar" class="btn btn-primary me-1">
                            <a href="{% url 'supplier-detail' pk_int %}" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

supplier/templates/supplier/CRUD/address_supplier/delete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Confirmation Delete</title>
{% endblock %}


{% block content %}
    <div class="container">
        <form class="jumbotron" method="post">
            {% csrf_token %}
            <h2>Deseja realmente excluir o Endereço   
                <span class="text-danger">        
                    {{ object }}
                </span>?
            </h2>
            <div class="btn-group" role="group" aria-label="First group">
                <input type="submit" value="Excluir" class="btn btn-group btn-danger">
                <a href="{% url 'supplier-detail' object.supplier.id %}"><input type="button"  class="btn btn-group btn-success" value="Cancelar">
            </div>
        </form>
    </div>
{% endblock %}

supplier/templates/supplier/CRUD/address_supplier/update.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container p-2 mt-4">
    <div class="row"> 
        <div class="col-12"> 
            <div class="card"> 
                <div class="card-header card-no-border pb-0">
                    <h3 class="text-center">Alterar o Endereço do Fornecedor</h3>
                </div>
                <div class="container">
                    <form action="" method="post" class="p-5 m-3">
                        {% csrf_token %}
                        <div id="div_id_address_type" class="mb-3"> 
                            <label for="id_address_type" class="form-label requiredField">Tipo de Endereço
                                <span class="asteriskField">*</span> 
                            </label> 
                            <select name="address_type" class="select form-select" required="" id="id_address_type"> 
                                <option value="" selected="">---------</option> 
                                <option value="RS"
                                    {% if object.address_type == 'RS' %}
                                        selected=""
                                    {% endif %}
                                >Residencial</option> 
                                <option value="CM"
                                    {% if object.address_type == 'CM' %}
                                        selected=""
                                    {% endif %}
                                >Comercial</option>
                                <option value="OT"
                                {% if object.address_type == 'OT' %}
                                        selected=""
                                    {% endif %}
                                >Outros</option>
                            </select> 
                        </div> 
                        <div id="div_id_zip_code" class="mb-3"> 
                            <label for="id_zip_code" class="form-label requiredField">
                                CEP<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="zip_code" maxlength="9" class="textinput form-control" required="" id="id_zip_code" value="{{ object.zip_code }}"> 
                        </div>
                        <div class="col-md-2 d-flex align-items-end">
                            <button type="button" class="btn btn-secondary btn-sm" onclick="buscarCEP()">Buscar</button>
                        </div>
                        <!-- Mensagem de erro -->
                        <p id="error-message" style="color: red;"></p>
                        
                        <div id="div_id_address" class="mb-3"> 
                            <label for="id_address" class="form-label requiredField">
                                Lougradouro<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="address" maxlength="100" class="textinput form-control" required="" id="id_address" value="{{ object.address }}">
                        </div> 
                        <div id="div_id_number" class="mb-3"> 
                            <label for="id_number" class="form-label requiredField">
                                Número<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="number" maxlength="5" class="textinput form-control" required="" id="id_number"value="{{ object.number }}"> 
                        </div> 
                        <div id="div_id_complement" class="mb-3"> 
                            <label for="id_complement" class="form-label requiredField">
                                Complemento 
                            </label> 
                            <input type="text" name="complement" maxlength="20" class="textinput form-control" id="id_complement"value="{{ object.complement }}"> 
                        </div> 
                        <div id="div_id_district" class="mb-3"> 
                            <label for="id_district" class="form-label requiredField">
                                Bairro<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="district" maxlength="70" class="textinput form-control" required="" id="id_district" value="{{ object.district }}"> 
                        </div> 
                        <div id="div_id_city" class="mb-3"> 
                            <label for="id_city" class="form-label requiredField">
                                Cidade<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="city" maxlength="70" class="textinput form-control" required="" id="id_city"value="{{ object.city }}"> 
                        </div> 
                        <div id="div_id_state" class="mb-3"> 
                            <label for="id_state" class="form-label requiredField">
                                UF<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="state" maxlength="2" class="textinput form-control" required="" id="id_state"value="{{ object.state }}"> 
                        </div> 
                        <div id="div_id_ibge_code" class="mb-3"> 
                            <label for="id_ibge_code" class="form-label requiredField">
                                Código IBGE<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="ibge_code" maxlength="10" class="textinput form-control" required="" id="id_ibge_code"value="{{ object.ibge_code }}"> 
                        </div> 
                        <div id="div_id_gia_code" class="mb-3"> 
                            <label for="id_gia_code" class="form-label requiredField">
                                Código GIA<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="gia_code" maxlength="6" class="textinput form-control" required="" id="id_gia_code"value="{{ object.gia_code }}"> 
                        </div> 
                        <div id="div_id_ddd_code" class="mb-3"> 
                            <label for="id_ddd_code" class="form-label requiredField">
                                Código DDD<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="ddd_code" maxlength="2" class="textinput form-control" required="" id="id_ddd_code"value="{{ object.ddd_code }}"> 
                        </div>
                        <div id="div_id_siafi_code" class="mb-3"> 
                            <label for="id_siafi_code" class="form-label requiredField">
                                Código SIAFI<span class="asteriskField">*</span> 
                            </label> 
                            <input type="text" name="siafi_code" maxlength="6" class="textinput form-control" required="" id="id_siafi_code"value="{{ object.siafi_code }}"> 
                        </div>
                        <div class="btn-group">
                            <input type="submit" value="Salvar" class="btn btn-primary me-1">
                            <a href="{% url 'supplier-detail' addresssupplier.supplier.id %}" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}