core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import IndexView, CustomLoginView, CustomLogoutView

urlpatterns = [
    path("", login_required(IndexView.as_view()), name='index'),
    path("supplier/", include('supplier.urls')),
    path("suppli_request/", include('suppli_request.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

supplier/urls.py
from django.urls import path, include

from supplier import views as v

urlpatterns = [
    path("", v.SupplierListView.as_view(), name="supplier-index"),
    path("Detail/<int:pk>/", v.SupplierDetailView.as_view(), name="supplier-detail"),
    path("Update/<int:pk>/", v.SupplierUpdateView.as_view(), name="supplier-update"),
    path("new", v.SupplierCreateView.as_view(), name="supplier-new"),    
    # path("detail", IndexView.as_view(), name="supplier-index"),
    path("ConfirmDelete/<int:pk>/",  v.SupplierDeleteView.as_view(), name="supplier-delete"),
    # CRUD phone_supplier
    path("NewPhoneNumber/<int:int>/", v.PhoneSupplierCreateView.as_view(), name="supplier-createphone"),
    path("UpdatePhoneNumber/<int:pk>/", v.PhoneSupplierUpdateView.as_view(), name="supplier-updatephone"),
    path("Phone/ConfirmDelete/<int:pk>/",  v.PhoneSupplierDeleteView.as_view(), name="supplier-deletephone"),
    # CRUD contact_supplier
    path("NewContact/<int:int>/", v.ContactSupplierCreateView.as_view(), name="supplier-createcontact"),
    path("UpdateContact/<int:pk>/", v.ContactSupplierUpdateView.as_view(), name="supplier-updatecontact"),
    path("Contact/ConfirmDelete/<int:pk>/",  v.ContactSupplierDeleteView.as_view(), name="supplier-deletecontact"),
    # CRUD phone contact_supplier
    path("NewPhoneContact/<int:int>/<int:int2>/", v.PhoneContactCreateView.as_view(), name="supplier-createphonecontact"),
    path("UpdatePhoneContact/<int:pk>/", v.PhoneContactUpdateView.as_view(), name="supplier-updatephonecontact"),
    path("PhoneContact/ConfirmDelete/<int:pk>/",  v.PhoneContactDeleteView.as_view(), name="supplier-deletephonecontact"),
    # CRUD address_supplier
    path("NewAddressNumber/<int:int>", v.AddressSupplierCreateView.as_view(), name="supplier-createaddress"),
    path("UpdateAddressNumber/<int:pk>/", v.AddressSupplierUpdateView.as_view(), name="supplier-updateaddress"),
    path("Address/ConfirmDelete/<int:pk>/",  v.AddressSupplierDeleteView.as_view(), name="supplier-deleteaddress"),
]

supplier/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

USER = get_user_model()


# Abstracts Models
class PhoneBase(models.Model):
    class TypePhoneChoice(models.TextChoices):
        LANDLINE = "LL", _("Telefone Fixo")
        MOBILE = "MB", _("Celular")
    """Model definition for PhoneContact."""
    
    type_phone = models.CharField(_("Telefone"), max_length=2, choices=TypePhoneChoice.choices, default="MB")
    ddi_number = models.CharField(_("DDI"), max_length=3, null=True, blank=True)
    ddd_number = models.CharField(_("DDD"), max_length=2, null=False, blank=False)
    phone_number = models.CharField(_("Número"), max_length=9, null=False, blank=False)

    class Meta:
        abstract = True


class TimeStampBase(models.Model):
    
    created = models.DateTimeField(_("Criado em"), auto_now=False, auto_now_add=True)
    modified = models.DateTimeField(_("Modificado em"), auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(
        USER, 
        verbose_name=_("Usuário"), 
        on_delete=models.CASCADE
    )
    class Meta:
        abstract = True


class AddressBase(models.Model):
    zip_code = models.CharField(_("CEP"), max_length=9)
    address = models.CharField(_("Lougradouro"), max_length=100)
    district = models.CharField(_("Bairro"), max_length=70)
    city = models.CharField(_("Cidade"), max_length=70)
    state = models.CharField(_("UF"), max_length=2)
    ibge_code = models.CharField(_("Código IBGE"), max_length=10)
    gia_code = models.CharField(_("Código GIA"), max_length=6)
    ddd_code = models.CharField(_("Código DDD"), max_length=2)
    siafi_code = models.CharField(_("Código SIAFI"), max_length=6)

    class Meta:
        abstract = True


# Create your models here.
class Supplier(TimeStampBase):   
    """Model definition for Supplier."""
    
    
    is_active = models.BooleanField(_("Ativo"), default=True)
    company_name = models.CharField(_("Razão Social"), max_length=150, null=False, blank=False)
    fantasy_name = models.CharField(_("Nome Fantasia"), max_length=150, null=True, blank=True)
    cnpj_number = models.CharField(_("CNPJ"), max_length=14, null=False, blank=True)
    e_mail = models.EmailField(_("E-mail"), max_length=254, blank=True, null=True)
    class Meta:
        """Meta definition for Supplier."""

        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
    
    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        """Unicode representation of Supplier."""
        if self.fantasy_name:
            return self.fantasy_name.title()
        return self.company_name
    
    def get_active(self):
        active = 1
        print(active)
        return active

class ContactSupplier(models.Model):
    """Model definition for ContactSupplier."""

    supplier_id = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedores"),
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(_("Nome"), max_length=30, null=False, blank=False)
    last_name = models.CharField(_("Sobrenome"), max_length=50, null=True, blank=True)
    position_company = models.CharField(_("Cargo na Empresa"), max_length=50, null=False, blank=False)
    e_mail = models.EmailField(_("E-mail"), max_length=254, null=False, blank=False)
    remarks = models.CharField(_("Observações"), max_length=254, null=True, blank=True)

    class Meta:
        """Meta definition for ContactSupplier."""

        verbose_name = 'Contato do Fornecedor'
        verbose_name_plural = 'Contatos dos Fornecedores'

    @property
    def full_name(self):
        if self.last_name:
            return f'{self.first_name.title()} {self.last_name.title()}'
        return f'{self.first_name.title()}'
    
    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.supplier_id.pk})
    
    def __str__(self):
        """Unicode representation of ContactSupplier."""
        
        return f'{self.full_name.title()} - {self.position_company.title()}'


class PhoneContact(PhoneBase):

    contact = models.ForeignKey(
        ContactSupplier, 
        verbose_name=_("Contato"), 
        on_delete=models.CASCADE,
    )
    
    class Meta:
        """Meta definition for PhoneContact."""

        verbose_name = 'Telefones do Contato'
        verbose_name_plural = 'Telefones dos Contatos'

    def __str__(self):
        """Unicode representation of PhoneContact."""
        if self.ddi_number:
            return f'+{self.ddi_number} ({self.ddd_number}) {self.phone_number}'
        return f'({self.ddd_number}) {self.phone_number}'


class PhoneSupplier(PhoneBase):

    supplier_id = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE,
    )

    class Meta:
        """Meta definition for PhoneContact."""

        verbose_name = 'Telefones do Contato'
        verbose_name_plural = 'Telefones dos Contatos'

    def __str__(self):
        """Unicode representation of PhoneContact."""
        if self.ddi_number:
            return f'+{self.ddi_number} ({self.ddd_number}) {self.phone_number}'
        return f'({self.ddd_number}) {self.phone_number}'

    def get_absolute_url(self):
        return reverse("supplier-detail", kwargs={"pk": self.supplier_id.pk})


class ResquestSupplier(models.Model):
    class StatusChoice(models.TextChoices):
        INITIATED = "IT", _("Iniciado")
        PARALYZED = "PL", _("Paralizado")
        INPROGRESS = "IP", _("Em andamento")
        FINISHED = "FN", _("Finalizado")
        COMPLETED = "CP", _("Concluido")    
    """Model definition for ResquestSupplier."""

    supplier_id = models.ForeignKey(
        Supplier,
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE),
    request_date = models.DateField(_("Data da Requisição"), null=False, blank=False)
    reson_hiring = models.CharField(_("Motivo da Contratação"), max_length=254, null=False, blank=False)
    contract_value = models.FloatField(_("Valor Total do Contrato"), null=False, blank=False)
    status = models.CharField(_("Status"), max_length=2, choices=StatusChoice.choices, default="IT")

    class Meta:
        """Meta definition for ResquestSupplier."""

        verbose_name = 'Requisição ao Fornecedor'
        verbose_name_plural = 'Requisições aos Fornecedores'

    def __str__(self):
        """Unicode representation of ResquestSupplier."""
        return f'{self.supplier_id} - Data {self.request_date} - Valor Total R$ {self.contract_value}'


class AddressSupplier(AddressBase):
    class TypeAddressChoice(models.TextChoices):
        RESIDENTIAL = 'RS', _('Residencial')
        COMMERCIAL = 'CM', _('Comercial')
        OTHERS = 'OT', _('Outros')
        
    supplier = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedor"), 
        on_delete=models.CASCADE,
    )
    address_type = models.CharField(_("Tipo de Endereço"), max_length=2, choices=TypeAddressChoice.choices)
    number = models.CharField(_("Número"), max_length=5)
    complement = models.CharField(_("Complemento"), max_length=20, null=True, blank=True)

    class Meta:
        """Meta definition for Supplier."""

        verbose_name = 'Endereço do Fornecedor'
        verbose_name_plural = 'Endereços dos Fornecedores'

    def __str__(self):
        """Unicode representation of Supplier."""
        return f'{self.address_type} - {self.zip_code}-{self.address} {self.number} {self.complement} - {self.city}/{self.state}'

supplier/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from django.utils.translation import gettext as _

from .models import Supplier, PhoneSupplier

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, Row, Column


PhoneSupplierFormset = inlineformset_factory(Supplier, PhoneSupplier, fields=('type_phone', 'ddi_number', 'ddd_number', 'phone_number'), extra=3)


class SupplierForm(forms.ModelForm):
    
    class Meta:
        model = Supplier
        fields = '__all__'


class PhoneSupplierForm(forms.ModelForm):
    
    class Meta:
        model = PhoneSupplier
        fields = '__all__'

supplier/templates/supplier/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="page-wrapper compact-wrapper mt-5" id="pageWrapper"> 
    <div class="page-body">
        <div class="container-fluid general-widget">
            <div class="row"> 
                <div class="col-12"> 
                    <div class="card">
                        <div class="card-body">
                            <div class="row g-xl-5 g-3">
                                <div class="col-xxl-12 col-xl-12 box-col-12 position-relative">                            
                                    <div class="tab-content" id="supplier-pills-tabContent">
                                        <div class="tab-pane fade show active" id="contacts-supplier" role="tabpanel" aria-labelledby="contacts-supplier-tab">
                                            <div class="sidebar-body">
                                                <div class="card-header card-no-border pb-0 text-center">
                                                    <h3>Lista de Fornecedores Cadastrados</h3>
                                                    <p class="text-center">Clique na Razão Social do fornecedor desejado para obter mais informações!</p>
                                                </div>
                                                <div class="btn-toolbar justify-content-between p-3" role="toolbar" aria-label="Toolbar with button groups">
                                                    <div class="btn-group" role="group" aria-label="First group">
                                                        <a href="{% url 'supplier-new' %}" class="transparent-button">
                                                            <input type="button" value="Novo" class="btn">
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="container-fluid table-overflow">
                                                    {% if supplier_list %}
                                                        <table class="table table- table-striped table-hover table-sm">
                                                            <thead>
                                                                <tr role="row">
                                                                    <th class="sorting_disabled" rowspan="1" colspan="1" >ID</th>
                                                                    <th class="sorting_disabled" rowspan="1" colspan="1" >Razão Social</th>
                                                                    <th class="sorting_disabled" rowspan="1" colspan="1" >E-mail</th>
                                                                    <th class="text-center sorting_disabled" rowspan="1" colspan="1">Ativo</th>
                                                                    <th class="text-center sorting_disabled" rowspan="1" colspan="1">Ações</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                            {% for supplier in supplier_list %}
                                                                <tr role="row" class="odd">
                                                                    <td>
                                                                        <h6 class="f-w-600">{{ supplier.pk }}</h6>
                                                                    </td>
                                                                    <td>
                                                                        <div class="d-flex align-items-center gap-3">
                                                                            <div class="flex-shrink-0 comman-round">
                                                                                <img src="{% static 'img/1.png' %}" alt="">
                                                                            </div>
                                                                            <div class="flex-grow-1"><a href="{% url 'supplier-detail' supplier.id %}">
                                                                                <h6>{{ supplier.company_name }}</h6></a>
                                                                                <p>{{ supplier.fantasy_name }}</p>
                                                                                <p>CNPJ: {{ supplier.cnpj_number }}</p>
                                                                            </div>
                                                                        </div>
                                                                    </td>
                                                                    <td class="f-w-600">{{ supplier.e_mail }}</td>
                                                                    <td class="f-w-600 text-center">
                                                                        {% if supplier.is_active %}
                                                                            <i class="bi bi-check2 text-success"></i>
                                                                        {% else %}
                                                                            <i class="bi bi-x-lg text-danger"></i>
                                                                        {% endif %}
                                                                    </td>
                                                                    <td class="text-center">
                                                                        <a href="{% url 'supplier-update' supplier.id %}" ><i class="bi bi-pencil-square text-primary"></i></a>
                                                                        |  
                                                                        <a href="{% url 'supplier-delete' supplier.id %}?next={{ request.path|urlencode }}"><i class="bi bi-trash-fill text-danger"></i></a>
                                                                    </td>
                                                                </tr>
                                                            {% endfor %}
                                                            </tbody> 
                                                        </table>
                                                        <div class="input-group">
                                                            <div class="d-flex align-self-end p-2">
                                                                {% include 'partial/_pagination.html' %}
                                                            </div>
                                                        </div>      
                                                        {% else %}
                                                            <p>There are no books in the library.</p>
                                                        {% endif %}
                                                    </div>        
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}