core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import IndexView, CustomLoginView, CustomLogoutView

urlpatterns = [
    path("", login_required(IndexView.as_view()), name='index'),
    path("supplier/", include('supplier.urls')),
    path("suppli_request/", include('suppli_request.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

suppli_request/urls.py
from django.urls import path, include
from suppli_request import views

urlpatterns = [
    path("", views.SupplyResquestListView.as_view(), name="suppli_request-index"),
    # CRUD
    path("NewRequest/", views.SupplyRequestCreateView.as_view(), name="suppli_request-new"),
    path("UpdateRequest/<int:pk>/", views.SupplyRequestUpdateView.as_view(), name="suppli_request-update"),
    path("DeleteRequest/<int:pk>/", views.SupplyRequestDeleteView.as_view(), name="suppli_request-delete"),
    path("Detail/<int:pk>/", views.SupplyRequestDetailView.as_view(), name="suppli_request-detail"),
    path("AddSupplierRequest/<int:pk>/", views.SupplyRequestSupplierUpdateView.as_view(), name="suppli_request-update-supplier"),
    path("AddItensRequest/<int:int>/", views.SupplyItensRequestCreateView.as_view(), name="suppli_request-additens_request"),
    path("UpdateItemRequest/<int:pk>/", views.SupplyItensRequestUpdateView.as_view(), name="suppli_request-updateitem_request"),
    path("DeleteItemRequest/<int:pk>/", views.SupplyItensRequestDeleteView.as_view(), name="suppli_request-deleteitem_request"),
]

suppli_request/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from supplier.models import TimeStampBase, Supplier

USER = get_user_model()


#TextChoice
class StatusRequestChoice(models.TextChoices):
    STARTED = "ST", _('Iniciado')
    INPROGRESS = "IP", _('Em Andamento')
    CLOSED = "CS", _('Fechado')
    COMPLETED = 'CP', _('Finalizado')
    CANCELLED = 'CC', _('Cancelado')


class UnitItemRequestChoice(models.TextChoices):
    UNIT = "UNI", _('Unidade')
    BOX = "BOX", _('Caixa')
    KILOGRAM = "KG", _('Kilograma')
    BUCKET = "BCK", _("Balde")
    TRAY = "TRY", _('Bandeja')
    BAR = "BAR", _("Barra")
    BLOCK = "BLK", _("Bloco")
    BOBBIN = "BOB", _('Bobina')
    CAPSULE = "CAPS", _('Capsula')
    CARD = "CART", _('Cartela')
    HUNDRED = "HUNDRED", _('Cento')
    OFSET = "SET", _('Conjuento')
    CENTIMETER = "CM", _('Centimetro')
    CENTIMETERSQUARE = "CM2", _('Centrimetro Quadrado')
    DISPLAY = "DISP", _('Display')
    DOZEN = "DOZEN", _('Duzia')
    PACKAGE = "PACKAGE", _('Embalagem')
    BALE = "BALE", _('Fardo')
    SHEET = "SHEET", _('Folha') 
    GALLON = "GALLON", _('Galão')
    BOTTLE = "GF", _('Frasco')
    GRAMS = "GRAMS", _('Gramas')
    GAME = "GAME", _('Jogo')
    KIT = "KIT", _('Kit')
    CAN = "CAN", _('Lata')
    LITER = "LITER", _('Litro')
    METER = "M", _('Metro')
    SQUAREMETER = "M2", ('Metro Quadrado')
    CUBICMETER = "M3", _('Metro Cúbico')
    THOUSAND = "THOUSAND", _('Milheiro')
    MILLILITRE = "ML", _('Mililitro')
    MEGAWATTHOUR = "MWH", _('MegaWhats/Hora')
    PALLET = "PALLET", _('Palete')
    PAIRS = "PAIRS", _('Pares')
    PIECE = "PC", _('Peça')
    PATTER = "POT", ("Pote")
    CARAT = "K", _('Kilate')
    REAM = "REAM", _('Resma')
    ROLL = "ROLL", _('Rolo')
    BAG = "BAG", _("Saco")
    DRUM = "DRUM", _('Tambor')
    TANK = "TANK", _('Tanque')
    TON = "TON", _('Tonelada')
    TUBE = "TUBE", ('Tubo')
    VESSEL = "VESL", ('Vasilhame')
    GLASS = "GLASS", _('Vidro')


# Models
class SupplyResquest(TimeStampBase):
    date_request = models.DateField(_("Data da Requisição"))
    description_request = models.CharField(_("Descrição da Requisição"), max_length=150)
    status = models.CharField(_("Status"), max_length=2, choices=StatusRequestChoice.choices)
    supplier = models.ForeignKey(
        Supplier, 
        verbose_name=_("Fornecedor"), 
        on_delete=models.DO_NOTHING,
        blank=True, null=True
    )
    start_date = models.DateField(_("Inicio do Contrato"), blank=True, null=True)
    delivery_time = models.DateField(_("Prazo de Entrega"), blank=True, null=True)

    class Meta:
        """Meta definition for SuppliResquest."""

        verbose_name = 'Requisição de Fornecimento'
        verbose_name_plural = 'Requisições de Fornecimento'

    @property
    def get_value_total(self)-> float:
        itens = ItensSupplyRequest.objects.filter(supply_request=self.id)
        print(itens)
        value_total = 0.00
    
        for iten in itens:
            value_total += iten.value_total_itens_supply_request
        return value_total
    get_value_total.fget.short_description = 'Valor Total da Requisição'
    
    @property
    def get_unit_total(self) -> int:
        itens = ItensSupplyRequest.objects.filter(supply_request=self.id)
        unit_total = 0
    
        for iten in itens:
            unit_total += iten.amount_item
        return unit_total
    get_unit_total.fget.short_description = "Quantidade Total de Itens"
    
    def get_absolute_url(self):
        return reverse("suppli_request-detail", kwargs={"pk": self.pk})

    @property
    def get_total(self):
        value = ""
        return sum([value for value_total_itens_supply_request in self.ItensSupplyRequest.filter(supply_request=self)])
    
    def __str__(self):
        """Unicode representation of SuppliResquest."""
        return f'{self.description_request.capitalize()} - {self.status}'


class ItensSupplyRequest(models.Model):
    supply_request = models.ForeignKey(
        SupplyResquest, 
        verbose_name=_("Requisição de Fornecimento"), 
        on_delete=models.CASCADE,
    )
    code_item_request = models.CharField(_("Código do Item Requisitado"), max_length=30)
    description_item = models.CharField(_("Descrição do Item Requisitado"), max_length=200)
    amount_item = models.PositiveIntegerField(_("Quantidade"))
    unit_measurement = models.CharField(_("Unidade"), max_length=8, choices=UnitItemRequestChoice.choices)
    unit_value = models.FloatField(_("Valor Unitãrio"), )
    total_value = models.FloatField(_("Valor Total"), blank=True, null=True)

    class Meta:
        """Meta definition for ItensSupplyRequest."""
        verbose_name = 'ItensSupplyRequest'
        verbose_name_plural = 'ItensSupplyRequests'
        
    @property
    def value_total_itens_supply_request(self):
        total = self.amount_item * self.unit_value
        return total
    
    def get_absolute_url(self):
        return reverse("suppli_request-detail", kwargs={"pk": self.supply_request.pk})
    
    def __str__(self):
        """Unicode representation of ItensSupplyRequest."""
        return f'{self.code_item_request} - {self.description_item}'

suppli_request/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, ListView, UpdateView
from django.views.generic.edit import DeleteView
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin


from suppli_request import models

# Create your views here.

# MIXINS
# VIEWS

class SupplyResquestListView(LoginRequiredMixin, ListView):
    model = models.SupplyResquest
    template_name = "suppli_request/index.html"
    if models.SupplyResquest.objects.exists():
        paginate_by = 10
    


class SupplyRequestCreateView(LoginRequiredMixin,CreateView):
    model = models.SupplyResquest
    template_name = "suppli_request/supplyrequest/CRUD/create.html"
    fields = ["date_request", "description_request", "status"]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class SupplyItensRequestCreateView(LoginRequiredMixin, CreateView):
    model = models.ItensSupplyRequest
    template_name = "suppli_request/supplyrequest/CRUD/itens/create.html"
    fields = ['code_item_request',
                'description_item',
                'amount_item',
                'unit_measurement',
                'unit_value',
            ]
    def get_context_data(self, **kwargs):
        context = super(SupplyItensRequestCreateView, self).get_context_data(**kwargs)
        
        pk_int = self.kwargs['int']
        context['pk_int'] = pk_int
        
        return context    
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        supply_request = models.SupplyResquest.objects.get(id=self.kwargs['int'])
        
        self.object.supply_request = supply_request
        print(self.object)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class SupplyRequestDetailView(LoginRequiredMixin, DetailView):
    model = models.SupplyResquest
    template_name = "suppli_request/supplyrequest/CRUD/detail.html"
    
    def get_context_data(self, **kwargs):
        context = super(SupplyRequestDetailView, self).get_context_data(**kwargs)
        
        itens = models.ItensSupplyRequest.objects.filter(supply_request=self.object)
        
        context['itens'] = itens
        
        return context


class SupplyRequestUpdateView(LoginRequiredMixin, UpdateView):
    model = models.SupplyResquest
    template_name = "suppli_request/supplyrequest/CRUD/update.html"    
    fields = ["date_request",
                "description_request",
                "status",
            ]

    def get_success_url(self):
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', '/'))
        return redirect_to    

class SupplyRequestSupplierUpdateView(LoginRequiredMixin, UpdateView):
    model = models.SupplyResquest
    template_name = "suppli_request/supplyrequest/CRUD/update_supplier.html"    
    fields = ["supplier",
                "start_date",
                'delivery_time',
            ]
    
    def get_success_url(self):
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', '/'))
        return redirect_to    

class SupplyItensRequestUpdateView(LoginRequiredMixin, UpdateView):
    model = models.ItensSupplyRequest
    template_name = "suppli_request/supplyrequest/CRUD/itens/update.html"    
    fields = ['code_item_request',
                'description_item',
                'amount_item',
                'unit_measurement',
                'unit_value',
            ]
    
    def get_success_url(self):
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', '/'))
        return redirect_to


class SupplyRequestDeleteView(LoginRequiredMixin, DeleteView):
    model = models.SupplyResquest
    template_name = "suppli_request/supplyrequest/CRUD/delete.html"    
    
    def get_success_url(self):
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', '/'))
        return redirect_to

class SupplyItensRequestDeleteView(LoginRequiredMixin, DeleteView):
    model = models.ItensSupplyRequest
    template_name = "suppli_request/supplyrequest/CRUD/itens/delete.html"
    
    def get_success_url(self):
        redirect_to = self.request.POST.get('next', self.request.GET.get('next', '/'))
        return redirect_to


# Views para Contato e Sobre
def contact(request):
    return render(request, 'contact.html')

def about(request):
    return render(request, 'about.html')

suppli_request/templates/suppli_request/supplyrequest/CRUD/partial/body.html
{% load static %}

<div class="col-xxl-9 col-xl-8 box-col-8 position-relative">                            
    <div class="tab-content" id="supplier-pills-tabContent">
        <div class="tab-pane fade show active" id="detail-supplier" role="tabpanel" aria-labelledby="detail-supplier-tab">
            {% include 'suppli_request/supplyrequest/CRUD/partial/detail-suppliyrequest.html' %}
        </div>
        <div class="tab-pane fade" id="contacts-supplier" role="tabpanel" aria-labelledby="contacts-supplier-tab">
            {% include 'suppli_request/supplyrequest/CRUD/partial/itensrequest.html' %}
        </div>        
    </div>
</div>

suppli_request/templates/suppli_request/supplyrequest/CRUD/partial/contracts-supplier.html
{% load static %}

suppli_request/templates/suppli_request/supplyrequest/CRUD/partial/detail-suppliyrequest.html
{% load static %}

<div class="sidebar-body">
    <div class="row custom-input">
        <div class="col-sm-1 mb-2">
            <label class="form-label" for="FormControlInput3">ID</label>
            <input class="form-control" id="FormControlInput3" type="text" value="{{ supplyresquest.id }}">
        </div>
        <div class="col-sm-3 mb-2">
            <label class="form-label" for="FormControlInput1">Data da Requisição</label>
            <input class="form-control" id="FormControlInput1" type="text" value="{{ supplyresquest.date_request }}">
        </div>
        <div class="col-sm-8 mb-2">
            <label class="form-label" for="FormControlInput4">Status</label>
            <input class="form-control" id="FormControlInput4" type="email" value="{{ supplyresquest.get_status_display }}">
        </div>
    </div>    
    <div class="row">
        <div class="col-12 mb-2">
                <label class="form-label" for="FormControlInput2">Descrição da Requisição</label>
            <i class="icon-help-alt ms-1" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="set proper weight for product items."></i>
        </div>
        <div class="col-12 mb-4">
            <textarea class="form-control" rows="10" name="description_request" id="FormControlInput2" type="multi-text">{{ supplyresquest.description_request }}</textarea>
        </div>
    </div>
    
</div>

suppli_request/templates/suppli_request/supplyrequest/CRUD/partial/itensrequest.html
{% load static %}

<div class="sidebar-body">
    <p class="text-center">Itens da Requsição</p>
    <div class="btn-toolbar justify-content-between p-3" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group" role="group" aria-label="First group">
            <a href="{% url 'suppli_request-additens_request' supplyresquest.id %}" class="transparent-button">
                <input type="button" value="Novo" class="btn">
            </a>
        </div>
    </div>
    <div class="container table-overflow">
        {% if itens %}
            <table class="table table table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Código do Item</th>
                        <th>Descrição do Item</th>
                        <th>Quantidade</th>
                        <th>unidade</th>
                        <th>Valor Unitário</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in itens %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.code_item_request }}</td>
                        <td>{{ item.description_item }}</td>
                        <td>{{ item.amount_item }}</td>
                        <td>{{ item.get_unit_measurement_display }}</td>
                        <td>{{ item.unit_value }}</td>
                        <td class="text-center">
                            <a href="{% url 'suppli_request-updateitem_request' item.id %}?next={{ request.path|urlencode }}" ><i class="bi bi-pencil-square text-primary"></i></a>
                            |  
                            <a href="{% url 'suppli_request-deleteitem_request' item.id %}?next={{ request.path|urlencode }}"><i class="bi bi-trash-fill text-danger"></i></a>
                        </td>
                    </tr>            
                {% endfor %}
                </tbody> 
            </table>        
            {% endif %}
        </div>        
    </div>
</div>

suppli_request/templates/suppli_request/supplyrequest/CRUD/partial/side.html
{% load static %}

<div class="col-xxl-3 col-xl-4 box-col-4e sidebar-left-wrapper">
    <ul class="sidebar-left-icons nav nav-pills" id="supplier-pills-tab" role="tablist">
        <li class="nav-item" role="presentation"> 
            <a class="nav-link active" id="detail-supplier-tab" data-bs-toggle="pill" href="#detail-supplier" role="tab" aria-controls="detail-supplier" aria-selected="true">
                <div class="nav-rounded">
                    <div class="supplier-icons">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-buildings stroke-icon" viewBox="0 0 16 16">
                            <path d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022M6 8.694 1 10.36V15h5zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5z"/>
                            <path d="M2 11h1v1H2zm2 0h1v1H4zm-2 2h1v1H2zm2 0h1v1H4zm4-4h1v1H8zm2 0h1v1h-1zm-2 2h1v1H8zm2 0h1v1h-1zm2-2h1v1h-1zm0 2h1v1h-1zM8 7h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zM8 5h1v1H8zm2 0h1v1h-1zm2 0h1v1h-1zm0-2h1v1h-1z"/>
                        </svg>
                    </div>
                </div>
                <div class="supplier-tab-content">
                    <h5>Requisição</h5>
                    <p>Informações principais da Requisição</p>
                </div>
            </a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="contacts-supplier-tab" data-bs-toggle="pill" href="#contacts-supplier" role="tab" aria-controls="contact-supplier" aria-selected="false" tabindex="-1">
                <div class="nav-rounded">
                    <div class="supplier-icons">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                            <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                            <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
                        </svg>
                    </div>
                </div>
                <div class="supplier-tab-content">
                    <h5>Itens da Requisição</h5>
                    <p>Código, descrição e quantidade</p>
                </div>
            </a>
        </li>
    </ul>
</div>